"""Volunteer services and favorite missions

Revision ID: 0e12f1acb42c
Revises: 370a15506858
Create Date: 2026-01-07 13:38:54.446270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e12f1acb42c'
down_revision: Union[str, Sequence[str], None] = '370a15506858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply this migration: create the `favorite` association table and remove mission count columns from `volunteer`.

    Creates table `favorite` with columns `id_volunteer` (Integer, not null), `id_mission` (Integer, not null), and `created_at` (DateTime, not null); adds foreign keys to `volunteer.id_volunteer` and `mission.id_mission` and a composite primary key on (`id_volunteer`, `id_mission`). Removes the `active_missions_count` and `finished_missions_count` columns from the `volunteer` table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id_volunteer', sa.Integer(), nullable=False),
    sa.Column('id_mission', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_mission'], ['mission.id_mission'], ),
    sa.ForeignKeyConstraint(['id_volunteer'], ['volunteer.id_volunteer'], ),
    sa.PrimaryKeyConstraint('id_volunteer', 'id_mission')
    )
    op.drop_column('volunteer', 'active_missions_count')
    op.drop_column('volunteer', 'finished_missions_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the migration that created the favorite association and removed mission count columns.

    Restores the `finished_missions_count` and `active_missions_count` integer columns on the `volunteer` table (non-nullable) and removes the `favorite` association table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default to handle existing rows
    op.add_column('volunteer', sa.Column('finished_missions_count', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text("0")))
    op.add_column('volunteer', sa.Column('active_missions_count', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text("0")))
    # Remove the server defaults to match original schema
    op.alter_column('volunteer', 'finished_missions_count', server_default=None)
    op.alter_column('volunteer', 'active_missions_count', server_default=None)
    op.drop_table('favorite')
    # ### end Alembic commands ###
