"""Admin have unique email

Revision ID: 146aca8c125a
Revises: f8e229cd6650
Create Date: 2026-01-06 21:24:13.284104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '146aca8c125a'
down_revision: Union[str, Sequence[str], None] = 'f8e229cd6650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=False)
    # ### end Alembic commands ###
