"""Admin have unique email

Revision ID: 146aca8c125a
Revises: f8e229cd6650
Create Date: 2026-01-06 21:24:13.284104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '146aca8c125a'
down_revision: Union[str, Sequence[str], None] = 'f8e229cd6650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Enforce a unique constraint on the admin table's email column.

    Drops the existing index on admin.email and recreates it as a unique index named ix_admin_email so that email values must be unique.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the admin.email index to a non-unique index.

    Drops the unique index on the admin.email column and recreates a non-unique index named ix_admin_email.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=False)
    # ### end Alembic commands ###
