"""Add report enums and validations

Revision ID: 26d3be42dbb3
Revises: 0e12f1acb42c
Create Date: 2026-01-07 19:28:51.553209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26d3be42dbb3'
down_revision: Union[str, Sequence[str], None] = '0e12f1acb42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types
    reporttype_enum = sa.Enum('HARASSMENT', 'INAPPROPRIATE_BEHAVIOR', 'SPAM', 'FRAUD', 'OTHER', name='reporttype')
    reporttarget_enum = sa.Enum('PROFILE', 'MESSAGE', 'MISSION', 'OTHER', name='reporttarget')
    reporttype_enum.create(op.get_bind(), checkfirst=True)
    reporttarget_enum.create(op.get_bind(), checkfirst=True)

    # Convert columns to enum with USING clause
    op.execute("ALTER TABLE report ALTER COLUMN type TYPE reporttype USING type::reporttype")
    op.execute("ALTER TABLE report ALTER COLUMN target TYPE reporttarget USING target::reporttarget")

    # Make columns NOT NULL
    op.alter_column('report', 'type', nullable=False)
    op.alter_column('report', 'target', nullable=False)
    op.alter_column('report', 'reason', existing_type=sa.VARCHAR(length=500), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'reason',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('report', 'target',
               existing_type=sa.Enum('PROFILE', 'MESSAGE', 'MISSION', 'OTHER', name='reporttarget'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('report', 'type',
               existing_type=sa.Enum('HARASSMENT', 'INAPPROPRIATE_BEHAVIOR', 'SPAM', 'FRAUD', 'OTHER', name='reporttype'),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    # Drop the enum types to avoid orphaned types on re-apply
    op.execute("DROP TYPE IF EXISTS reporttype")
    op.execute("DROP TYPE IF EXISTS reporttarget")
    # ### end Alembic commands ###
