"""add hashed_refresh_token to user and admin

Revision ID: 288dd6e558eb
Revises: 26d3be42dbb3
Create Date: 2026-01-10 19:03:05.392349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '288dd6e558eb'
down_revision: Union[str, Sequence[str], None] = '26d3be42dbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('hashed_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('hashed_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_refresh_token')
    op.drop_column('admin', 'hashed_refresh_token')
    # ### end Alembic commands ###
