"""fix user date creation and notification index

Revision ID: 32ee6493ed3c
Revises: a5e891d45c62
Create Date: 2026-01-12 00:04:26.053338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32ee6493ed3c'
down_revision: Union[str, Sequence[str], None] = 'a5e891d45c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_association'), table_name='notification')
    op.create_index(op.f('ix_notification_id_asso'), 'notification', ['id_asso'], unique=False)
    op.alter_column('user', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_creation',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_id_asso'), table_name='notification')
    op.create_index(op.f('ix_notification_association'), 'notification', ['id_asso'], unique=False)
    # ### end Alembic commands ###
