"""Less restrictive phones and zip code limits and phone addition for association

Revision ID: 370a15506858
Revises: 146aca8c125a
Create Date: 2026-01-06 21:35:00.015842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '370a15506858'
down_revision: Union[str, Sequence[str], None] = '146aca8c125a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to relax length constraints and add an association phone number.

    Adds a non-nullable `phone_number` column (length 20) to the `association` table; changes `association.zip_code` to length 20 (remains non-nullable); changes `volunteer.phone_number` to length 20 (remains non-nullable); and changes `volunteer.zip_code` to length 20 (remains nullable).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default to handle existing rows, then remove the default
    op.add_column('association', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default=sa.text("''")))
    op.alter_column('association', 'phone_number', server_default=None)
    op.alter_column('association', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('volunteer', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('volunteer', 'zip_code',
               existing_type=sa.VARCHAR(length=9),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer', 'zip_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('volunteer', 'phone_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('association', 'zip_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('association', 'phone_number')
    # ### end Alembic commands ###
