"""added notification category and location logic

Revision ID: a5e891d45c62
Revises: 410f8d3a5fac
Create Date: 2026-01-11 22:54:53.258029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e891d45c62'
down_revision: Union[str, Sequence[str], None] = '410f8d3a5fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_category')
    op.alter_column('association', 'verification_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='processingstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_association'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_constraint(op.f('notification_related_user_id_fkey'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('notification_id_asso_fkey'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('notification_related_mission_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key('notification_related_mission_id_fkey', 'notification', 'mission', ['related_mission_id'], ['id_mission'], ondelete='CASCADE')
    op.create_foreign_key('notification_related_user_id_fkey', 'notification', 'user', ['related_user_id'], ['id_user'], ondelete='SET NULL')
    op.create_foreign_key('notification_id_asso_fkey', 'notification', 'association', ['id_asso'], ['id_asso'], ondelete='CASCADE')
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_association'), 'notification', ['id_asso'], unique=False)
    op.alter_column('user', 'password_reset_expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_reset_expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint('notification_related_mission_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_related_user_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_id_asso_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_related_mission_id_fkey'), 'notification', 'mission', ['related_mission_id'], ['id_mission'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notification_id_asso_fkey'), 'notification', 'association', ['id_asso'], ['id_asso'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notification_related_user_id_fkey'), 'notification', 'user', ['related_user_id'], ['id_user'], ondelete='SET NULL')
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_association'), 'notification', ['id_asso'], unique=False)
    op.alter_column('notification', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('notification', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('association', 'verification_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='processingstatus'),
               server_default=sa.text("'PENDING'::processingstatus"),
               existing_nullable=False)
    op.create_table('mission_category',
    sa.Column('id_mission', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_categ', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_categ'], ['category.id_categ'], name=op.f('mission_category_id_categ_fkey')),
    sa.ForeignKeyConstraint(['id_mission'], ['mission.id_mission'], name=op.f('mission_category_id_mission_fkey')),
    sa.PrimaryKeyConstraint('id_mission', 'id_categ', name=op.f('mission_category_pkey'))
    )
    # ### end Alembic commands ###