"""User and Admin related tables consistency update

Revision ID: f8e229cd6650
Revises: fe5fe30b5dd1
Create Date: 2026-01-06 20:27:30.790937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8e229cd6650'
down_revision: Union[str, Sequence[str], None] = 'fe5fe30b5dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_association_address'), table_name='association')
    op.drop_index(op.f('ix_association_company_name'), table_name='association')
    op.drop_index(op.f('ix_association_country'), table_name='association')
    op.drop_index(op.f('ix_association_name'), table_name='association')
    op.drop_index(op.f('ix_association_zip_code'), table_name='association')
    op.alter_column('volunteer', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=False)
    op.alter_column('volunteer', 'zip_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer', 'zip_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('volunteer', 'phone_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_association_zip_code'), 'association', ['zip_code'], unique=False)
    op.create_index(op.f('ix_association_name'), 'association', ['name'], unique=False)
    op.create_index(op.f('ix_association_country'), 'association', ['country'], unique=False)
    op.create_index(op.f('ix_association_company_name'), 'association', ['company_name'], unique=False)
    op.create_index(op.f('ix_association_address'), 'association', ['address'], unique=False)
    # ### end Alembic commands ###
