"""User and Admin related tables consistency update

Revision ID: f8e229cd6650
Revises: fe5fe30b5dd1
Create Date: 2026-01-06 20:27:30.790937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8e229cd6650'
down_revision: Union[str, Sequence[str], None] = 'fe5fe30b5dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes: remove several association indexes and adjust volunteer contact fields.

    Drops the following indexes on the `association` table: `ix_association_address`,
    `ix_association_company_name`, `ix_association_country`, `ix_association_name`,
    and `ix_association_zip_code`. Alters `volunteer.phone_number` to use
    `AutoString(length=15)` (keeps non-nullable) and `volunteer.zip_code` to use
    `AutoString(length=9)` (remains nullable).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_association_address'), table_name='association')
    op.drop_index(op.f('ix_association_company_name'), table_name='association')
    op.drop_index(op.f('ix_association_country'), table_name='association')
    op.drop_index(op.f('ix_association_name'), table_name='association')
    op.drop_index(op.f('ix_association_zip_code'), table_name='association')
    op.alter_column('volunteer', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=False)
    op.alter_column('volunteer', 'zip_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the schema changes applied in the corresponding upgrade revision.

    Reverts volunteer.phone_number to VARCHAR(50) (non-nullable) and volunteer.zip_code to VARCHAR(50) (nullable), and recreates the association table indexes: ix_association_zip_code, ix_association_name, ix_association_country, ix_association_company_name, and ix_association_address.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer', 'zip_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('volunteer', 'phone_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_association_zip_code'), 'association', ['zip_code'], unique=False)
    op.create_index(op.f('ix_association_name'), 'association', ['name'], unique=False)
    op.create_index(op.f('ix_association_country'), 'association', ['country'], unique=False)
    op.create_index(op.f('ix_association_company_name'), 'association', ['company_name'], unique=False)
    op.create_index(op.f('ix_association_address'), 'association', ['address'], unique=False)
    # ### end Alembic commands ###
