"""Initial migration

Revision ID: fe5fe30b5dd1
Revises:
Create Date: 2026-01-03 00:24:25.959379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe5fe30b5dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_admin')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=False)
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('badge',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id_badge', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_badge')
    )
    op.create_index(op.f('ix_badge_title'), 'badge', ['title'], unique=True)
    op.create_table('category',
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_categ', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_categ')
    )
    op.create_table('location',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_location')
    )
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_type', sa.Enum('ADMIN', 'VOLUNTEER', 'ASSOCIATION', name='usertype'), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_type'), 'user', ['user_type'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('association',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('rna_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('id_asso', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_asso'),
    sa.UniqueConstraint('id_user')
    )
    op.create_index(op.f('ix_association_address'), 'association', ['address'], unique=False)
    op.create_index(op.f('ix_association_company_name'), 'association', ['company_name'], unique=False)
    op.create_index(op.f('ix_association_country'), 'association', ['country'], unique=False)
    op.create_index(op.f('ix_association_name'), 'association', ['name'], unique=False)
    op.create_index(op.f('ix_association_rna_code'), 'association', ['rna_code'], unique=False)
    op.create_index(op.f('ix_association_zip_code'), 'association', ['zip_code'], unique=False)
    op.create_table('report',
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id_user_reporter', sa.Integer(), nullable=False),
    sa.Column('id_user_reported', sa.Integer(), nullable=False),
    sa.Column('id_report', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='processingstatus'), nullable=False),
    sa.Column('date_reporting', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user_reported'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['id_user_reporter'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_report')
    )
    op.create_table('volunteer',
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('id_volunteer', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('active_missions_count', sa.Integer(), nullable=False),
    sa.Column('finished_missions_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_volunteer'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('assign',
    sa.Column('id_volunteer', sa.Integer(), nullable=False),
    sa.Column('id_badge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_badge'], ['badge.id_badge'], ),
    sa.ForeignKeyConstraint(['id_volunteer'], ['volunteer.id_volunteer'], ),
    sa.PrimaryKeyConstraint('id_volunteer', 'id_badge')
    )
    op.create_table('document',
    sa.Column('doc_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_doc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('verif_state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='processingstatus'), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('id_asso', sa.Integer(), nullable=False),
    sa.Column('id_doc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['admin.id_admin'], ),
    sa.ForeignKeyConstraint(['id_asso'], ['association.id_asso'], ),
    sa.PrimaryKeyConstraint('id_doc')
    )
    op.create_table('mission',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('id_categ', sa.Integer(), nullable=False),
    sa.Column('id_asso', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=False),
    sa.Column('capacity_min', sa.Integer(), nullable=False),
    sa.Column('capacity_max', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_mission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_asso'], ['association.id_asso'], ),
    sa.ForeignKeyConstraint(['id_categ'], ['category.id_categ'], ),
    sa.ForeignKeyConstraint(['id_location'], ['location.id_location'], ),
    sa.PrimaryKeyConstraint('id_mission')
    )
    op.create_table('engagement',
    sa.Column('id_volunteer', sa.Integer(), nullable=False),
    sa.Column('id_mission', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='processingstatus'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_mission'], ['mission.id_mission'], ),
    sa.ForeignKeyConstraint(['id_volunteer'], ['volunteer.id_volunteer'], ),
    sa.PrimaryKeyConstraint('id_volunteer', 'id_mission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagement')
    op.drop_table('mission')
    op.drop_table('document')
    op.drop_table('assign')
    op.drop_table('volunteer')
    op.drop_table('report')
    op.drop_index(op.f('ix_association_zip_code'), table_name='association')
    op.drop_index(op.f('ix_association_rna_code'), table_name='association')
    op.drop_index(op.f('ix_association_name'), table_name='association')
    op.drop_index(op.f('ix_association_country'), table_name='association')
    op.drop_index(op.f('ix_association_company_name'), table_name='association')
    op.drop_index(op.f('ix_association_address'), table_name='association')
    op.drop_table('association')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_type'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('category')
    op.drop_index(op.f('ix_badge_title'), table_name='badge')
    op.drop_table('badge')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
